modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
modId = "pridelib"
version = "${version}"
displayName = "PrideLib-Forge"
credits="Emi, unascribed, LambdAurora, TexTrue"
authors = "TexTrueStudio, TexTrue"
description = '''
A unified library for data-driven flags"
'''
logoFile = "assets/pride/icon.png"

[[dependencies.pridelib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pridelib]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"