modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache-2.0"

[[mods]]
modId = "flagslib"
version = "${version}"
displayName = "FlagsLib-Forge"
credits="Emi, unascribed, LambdAurora, TexTrue"
authors = "TexTrueStudio, TexTrue"
description = '''
A unified library for data-driven flags"
'''
logoFile = "./assets/flagslib/icon.png"

[[dependencies.flagslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flagslib]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"